clist=['hello',1,2.0]
print(clist)
print(clist[1])
print(clist[-1])
clist=['hi',3,4.0]
print(clist)
clist[1]='hello'
clist.append("hello1")
print(clist)
clist.insert(2,'ABC')
print(clist)
clist1=[1,2,3,4]
clist1.extend(clist1)
print(clist)
clist.remove("ABC")
print(clist)
clist.pop()
print(clist)
clist.clear()